config/routes.rb
Rails.application.routes.draw do
  resources :couriers do
    resources :packages, shallow: true
  end
  root 'couriers#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/courier.rb
class Courier < ApplicationRecord
  has_many :packages, dependent: :destroy
  validates :name, presence: true, length: { maximum: 60 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 25 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
end

app/models/package.rb
class Package < ApplicationRecord
  belongs_to :courier
  validates :tracking_number, presence: true, length: { maximum: 15 }

  def humanized_delivery_status
    delivery_status ? 'Delivered' : 'Lost'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/couriers_controller.rb
class CouriersController < ApplicationController
  before_action :find_courier, only: [:show, :edit, :update, :destroy]
  def index
    @couriers = Courier.all
  end

  def new
    @courier = Courier.new
  end

  def create
    @courier = Courier.create(permitted_params)
    if @courier.valid?
      redirect_to courier_path(@courier), notice: 'Courier was successfully created.'
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @courier.update(permitted_params)
      redirect_to courier_path(@courier), notice: 'Courier was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @courier.destroy
    redirect_to couriers_path
  end

  private

  def permitted_params
    params.require(:courier).permit(:name, :email)
  end

  def find_courier
    @courier = Courier.find(params[:id])
  end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  before_action :find_package, only: [:show, :edit, :update, :destroy]
  def new
    @package = Package.new
  end

  def create
    @package = Package.create(permitted_params.merge(courier_id: params[:courier_id]))
    if @package.valid?
      redirect_to package_path(@package), notice: 'Package was successfully created.'
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @package.update(permitted_params)
      redirect_to package_path(@package), notice: 'Package was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @package.destroy
    redirect_to courier_path(@package.courier)
  end

  private

  def permitted_params
    params.require(:package).permit(:tracking_number, :delivery_status)
  end

  def find_package
    @package = Package.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/couriers/_form.html.erb
<% if @courier.errors.any? %>
  <div class="alert alert-danger">
    <p><%= pluralize(@courier.errors.count, "error") %> prohibited this courier from being saved:</p>

    <ul>
      <% @courier.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="row">
  <div class="col-6">
    <%= form_with(model: @courier, local: true) do |form| %>
      <div class='form-group'>
        <%= form.label :name, for: 'input_name' %>
        <%= form.text_field :name, id: 'input_name', class: 'form-control', placeholder: 'Enter name', autofocus: true %>
      </div>

      <div class='form-group'>
        <%= form.label :email, for: 'input_email' %>
        <%= form.text_area :email, id: 'input_email', class: 'form-control', placeholder: 'Enter email' %>
        <small id="email_help" class="form-text text-muted">We'll never share your email with anyone else.</small>
      </div>

      <div>
        <%= form.submit class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/couriers/edit.html.erb
<h1>Editing courier</h1>

<%= render partial: "form" %>
<br />
<%= link_to 'Show', @courier, class: 'btn btn-primary' %>
<%= link_to 'Back', couriers_path, class: 'btn btn-primary' %>

app/views/couriers/index.html.erb
<div class='pb-3'>
  <h1>Hello couriers!</h1>
  <%= link_to 'New', new_courier_path, class: 'btn btn-success' %>
</div>

<div class='row'>
  <% @couriers.each do |courier| %>
    <div class='col-3'>
      <div class='pb-3'>
        <div class='card text-center bg-light'>
          <div class='card-body'>
            <h5 class='card-title'><%= courier.name %></h5>
            <div class='card-text'><%= courier.email %></div>
            <br />
            <%= link_to 'Show', courier_path(courier), class: 'btn btn-primary' %>
            <%= link_to 'Edit', edit_courier_path(courier), class: 'btn btn-primary' %>
            <%= link_to 'Delete', courier, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/couriers/new.html.erb
<h1>Create courier</h1>

<%= render partial: "form" %>
<br />

<%= link_to 'Back', couriers_path, class: 'btn btn-primary' %>

app/views/couriers/show.html.erb
<% if notice %>
  <div class='alert alert-info'>
    <%= notice %>
  </div>
<% end %>

<div class='pb-3'>
  <h3>
    Hello, <%= @courier.name %>!
  </h3>
  <p><%= @courier.email %></p>
  <%= link_to 'Edit', edit_courier_path(@courier), :class => 'btn btn-primary'  %>
  <%= link_to 'Back', couriers_path, :class => 'btn btn-primary' %>
</div>

<div class='pb-3'>
  <h4>
  <%= @courier.name %>'s Packages
  </h4>
  <br />
  <%= link_to 'New',  new_courier_package_path(@courier), :class => 'btn btn-success'  %>
</div>

<div class='row'>
  <% @courier.packages.each do |package| %>
    <div class='col-3'>
      <div class='pb-3'>
        <div class='card-group'>
          <div class='card text-center bg-light'>
            <div class='card-body'>
              <div class='card-title'><%= package.tracking_number %></div>
              <div class='card-text'><%= package.humanized_delivery_status %></div>
              <br />
              <%= link_to 'Show', package_path(package), :class => 'btn btn-primary' %>
              <%= link_to 'Edit', edit_package_path(package), :class => 'btn btn-primary' %>
              <%= link_to 'Delete', package, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeliveryApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>